
# Stage 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy the .csproj and restore any dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy the rest of the source code and build the application
COPY . ./
RUN dotnet publish -c Release -o /app/out --runtime linux-x64  /p:PublishTrimmed=true

# Stage 2: Create the runtime environment
# # mcr.microsoft.com/dotnet/runtime-deps:8.0 AS runtime
# mcr.microsoft.com/dotnet/runtime:8.0-alpine AS runtime 
FROM mcr.microsoft.com/dotnet/runtime-deps:8.0 AS runtime
WORKDIR /app


# Copy the published application from the build stage
COPY --from=build-env /app/out ./

ENV Hostname=gateway.ocbc.com
ENV Nameserver=8.8.8.8
ENV NameserverPort=53
ENV MillisecondBetweenCalls=3000

# Set the entry point to run the app
ENTRYPOINT ["./main"]

