apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  gatewayocbccom.server: | # you may select any name here, but it must end with the .server file extension
    gateway.ocbc.com:53 {
      whoami
      errors
      log . "{type}: {name} requested by {remote} to {local}, duration: {duration}"
      forward . 168.63.129.16
    }