apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocbc-httpclient
  labels:
    app: ocbc-httpclient
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: ocbc-httpclient
  template:
    metadata:
      labels:
        app: ocbc-httpclient
    spec:
      containers:
      - name: myapp-container
        image: docker.io/wxzd/simulatenameunknown:v1  # Replace with your app image

        env:
        - name: Hostname
          value: "gateway.ocbc.com"
        - name: Nameserver
          value: "12.0.1.4" # custom dns server
        - name: NameserverPort
          value: "53"
        - name: MillisecondBetweenCalls
          value: "3000"

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "100m"